builds:
  - goos:
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - '386'
      - arm64
      - arm
    goarm:
      - '7'
      - '6'
    ignore:
      - goos: darwin
        goarch: '386'
      - goos: darwin
        goarch: arm
